version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl
      - curl -s -L https://github.com/gohugoio/hugo/releases/download/v0.147.6/hugo_0.147.6_linux-amd64.deb -o hugo.deb
      - dpkg -i hugo.deb
  build:
    commands:
      - echo Hugo Version
      - hugo version
      - echo Pulling theme code
      - git submodule update --init --recursive
      - cd src
      - pwd
      - ls -lhra
      - hugo --gc --minify
artifacts:
  files:
    - '**/*'
  base-directory: 'src/public'  