AWSTemplateFormatVersion: 2010-09-09
Description: Setup AWS environment using Route 53, Cloudfront and S3  for static website

Resources:
  # Here we have the S3 bucket that will host our files
  S3BucketStaticWebsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
  
  # Policy for the above S3 bucket
  # We need to allow cloudfront to access and get the objcets inside the s3 bucket
  S3BucketStaticWebsitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketStaticWebsite
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${S3BucketStaticWebsite}/*"
            Condition:
              StringEquals:
                  AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # Lets use Access Origin Control for our distribuition
  CloudFrontAOC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-OAC-${AWS::Region}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  
  # Then we create the our cloudfront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig:
        Comment: www.dstvsk.com.br
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3BucketStaticWebsite.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontAOC
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100 # Cheapest price class
  
Outputs:
  WebsiteUrl:
    Description: URL from Cloudfront Distribution
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
